packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - esbuild
  - workerd
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - hono@4.13.8
catalog:
  '@types/node': ^24.13.3
  typescript: ^5.9.3
  vitest: ^4.1.10
